# Generated by Django 6.0.1 on 2026-02-02 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcommunity', '0002_banner_notice_alter_welcome_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='igm',
            new_name='img',
        ),
    ]
