# Generated by Django 6.0.2 on 2026-02-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcommunity', '0004_area_userinfo_collection_area_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='face_token',
            field=models.CharField(max_length=64, null=True, verbose_name='百度Token'),
        ),
    ]
